const userData = {
  githubUsername: "raphsang",
  name: "Raphael Kipsang",
  designation: "Software Engineer",
  avatarUrl: "/profile.jpg",
  logoUrl: "/logo.png",
  Home: " @RaphSang",
  email: "kraftonerk2@gmail.com",
  phone: "+254716900335",
  address: "50, NAIROBI KENYA",
  projects: [{
      title: "NextJs blog page",
      link: "#",
      imgUrl: "/blog_page.png",
    },
    {
      title: "Vanilla JS blog page",
      link: "#",
      imgUrl: "/blogPage_.png",
    },
    {
      title: "Django Insurance management system",
      link: "#",
      imgUrl: "/homepage.png",
    },
    {
      title: "Loan Prediction system",
      link: "#",
      imgUrl: "/loan_prediction.png",
    },
    {
      title: "Simple Company Task Manager",
      link: "https://mockwebpage-raphsangs-projects.vercel.app/",
      imgUrl: "/company task manager.png",
    },
    {
      title: "Digital clock",
      link: "#",
      imgUrl: "/digital_clock.png",
    },
    {
      title: "Speed typing game",
      link: "#",
      imgUrl: "/speed_typing_game.png",
    },
  ],
  about: {
    title: "Skilled software engineer with a passion for creating efficient and reliable solutions. ",
    description: [
      `I have a strong passion for crafting efficient and scalable solutions. With a strong foundation in computer science and extensive industry experience, I consistently delivers high-quality code and drives successful project outcomes.`,
      `With expertise in various programming languages, frameworks, and technologies, I have a proven track record of designing and developing robust software applications. Their technical proficiency spans front-end and back-end development, including proficiency in languages such as JavaScript, Python, and Java.`,
      `Throughout my career, I collaborated with cross-functional teams to analyze requirements, architect software solutions, and implement best practices. They excel in problem-solving, leveraging their analytical mindset to identify and address complex challenges.`,
      `To sum up i'm talented software engineer who combines technical excellence, problem-solving abilities, and a strong work ethic to deliver exceptional software solutions. With a dedication to continuous improvement and a passion for innovation, they are poised to make significant contributions to the field of software engineering."`,
    ],
    
    currentProject: "Generative AI",
    currentProjectUrl: "#",
  },
  experience: [{
      title: "Intern",
      company: "Kenya Public Service (DLP)",
      year: "2024",
      companyLink: "#",
      desc: "Trained teachers on intergrating ICT on basic primary eductation.",
  },
  {
      title: "Post industrial attache",
      company: "Kenya Revenue Authority",
      year: "2023",
      companyLink: "#",
      desc: "worked as ICT support officer.",
  },

{
      title: "Student attache",
      company: "Baringo County Gvt",
      year: "2022",
      companyLink: "#",
      desc: "Contributed to our flagship product - Panna - which is an AI powered candidate interviewing product.",
    },
    {
      title: "Front Developer",
      company: "Upwork",
      year: "2021",
      companyLink: "#",
      desc: "Developed a marketplace for tailwind web components (React, HTML and CSS) and templates.",
    },
    {
      title: "University",
      company: "South Eastern Kenya University",
      year: "2023",
      companyLink: "#",
      desc: "First Class Honors",
    },
    {
      title: "High School",
      company: "Tiriondonin High",
      year: "2018",
      companyLink: "#",
      desc: "A- 75 points",
    },
    {
      title: "High School",
      company: "Moi High KBO",
      year: "2016",
      companyLink: "#",
      desc: "B 63 Points",
    },
    {
      title: "Primary School",
      company: "Kimugul Mixed Day School",
      year: "2012",
      companyLink: "#",
      desc: "B+ Marks 355/500",
    },
  ],
  resumeUrl: "https://drive.google.com/file/d/14O4fsJfje7-ePXIewsXHVOJvBIkCM8ij/view?usp=drivesdk",
  socialLinks: {
    instagram: "https://instagram.com/computersci3?igshid=ZDc4ODBmNjlmNQ==",
    twitter: "https://twitter.com/ruff_G",
    linkedin: "https://www.linkedin.com/in/raphael-kipsang",
    github: "https://github.com/raphsang",
    facebook: "https://www.facebook.com/computersci3",
  },
};

export default userData;
